# Generated by Django 3.2.14 on 2022-08-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
    ]
